---
book_repo: animatedmax/docs-book-pcfservices
layout_repo: animatedmax/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: animatedmax/docs-mysql
    ref: 1.8.0
  directory: p-mysql/1-8
  subnav_template: pivotal_edge_mysql_service_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/p-mysql/1-8/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: MySQL for PCF
    search_placeholder: Search MySQL for PCF 1.8
    url_prefix: p-mysql/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-mysql/1-7
        display_name: v1.7
